modLoader = "javafml"
loaderVersion = "[${versions.forge_dependency},)"
license = "MIT"

[[mods]]
modId = "caduceus"
version = "${version}"
displayName = "Caduceus"
logoFile = "assets/caduceus/icon.png"
authors = "object-Object"
description = "A Clojure-based Hex Casting addon for advanced meta-evaluation."

[[dependencies.caduceus]]
modId = "forge"
mandatory = true
versionRange = "[${versions.forge_dependency},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.caduceus]]
modId = "minecraft"
mandatory = true
versionRange = "[${versions.minecraft},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.caduceus]]
modId = "architectury"
mandatory = true
versionRange = "[${versions.architectury},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.caduceus]]
modId = "hexcasting"
mandatory = true
versionRange = "[${versions.hexcasting_dependency},)"
ordering = "NONE"
side = "BOTH"
